### ISSUE TITLE
this is another taskasdf

### ISSUE THREAD

**Issue by ohiosveryown** [ohiosveryown/supersymmetry#27]
- [ ] https://github.com/ohiosveryown/supersymmetry/issues/9
```[tasklist]
### Tasks
- [ ] https://github.com/ohiosveryown/supersymmetry/issues/28
- [ ] https://github.com/ohiosveryown/supersymmetry/issues/16
- [ ] https://github.com/ohiosveryown/supersymmetry/issues/8
```

```[tasklist]
### Tasks
```
