### ISSUE TITLE
feature engineering

### ISSUE THREAD

**Issue by ohiosveryown** [ohiosveryown/supersymmetry#30]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
---

```[tasklist]
### Tasks
- [ ] https://github.com/ohiosveryown/supersymmetry/issues/28
- [ ] Draft issue
```
- [x] https://github.com/github/accessibility-audits/issues/8072
- [ ] https://github.com/github/github/pull/333071

**Comment by ohiosveryown** [comment]
https://www.figma.com/design/Gd6Utx9cwNDoV0Ud6scesv/Apple-Design-Resources---visionOS-(Community)?node-id=221-56229&t=UI2hXEOP6B2O9bLs-1

[Figma link](https://www.figma.com/design/Gd6Utx9cwNDoV0Ud6scesv/Apple-Design-Resources---visionOS-(Community)?node-id=221-56229&t=UI2hXEOP6B2O9bLs-1)

#16 

- https://github.com/ohiosveryown/supersymmetry/issues/37
