### ISSUE TITLE
Compress Images

### ISSUE THREAD

**Issue by ohiosveryown** [ohiosveryown/supersymmetry#8]
## Epic description
Now that we’ve decided on our new rendering engine (see #824), we have some follow-up work to do. Let’s use this issue for tracking. I’ve taken a first pass at outstanding todos here.

```[tasklist]
### Tasks
- [ ] https://github.com/ohiosveryown/supersymmetry/issues/28
- [ ] https://github.com/ohiosveryown/supersymmetry/issues/26
- [ ] https://github.com/ohiosveryown/supersymmetry/issues/27
- [ ] Task
```

**Comment by ohiosveryown** [comment]
Ongoing but initially resolved with: c2a54ba4e3b110e2a50c7e5f44d0e6096123e770
