### ISSUE TITLE
404 Page

### ISSUE THREAD

**Issue by ohiosveryown** [ohiosveryown/supersymmetry#9]
Design and code 404 page.
![IMG_5121](https://user-images.githubusercontent.com/12748054/187960362-34cb4691-a0fa-4f94-8094-b30f56e72e8e.jpeg)

- [x] https://github.com/ohiosveryown/supersymmetry/issues/13#issue-499492313

https://github.com/ohiosveryown/supersymmetry/issues/9#tasklist-block-f2eabbcb-bf16-4f29-b0a4-31a9f5e5684b

```[tasklist]
### Tasks
- [x] https://github.com/ohiosveryown/supersymmetry/issues/31
- [x] task
- [ ] https://github.com/ohiosveryown/supersymmetry/issues/36
```
